# Generated by Django 5.1.1 on 2024-09-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
